substitutions:
  name: media-player-d396ab
  friendly_name: "Living Room Media Player"
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: "Living Room Media Player"
  build_flags:
      - "-DCONFIG_SPIRAM_USE_MALLOC=1"
      - "-DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=0"
api:
  encryption:
    key: GOdYEb8gh6jf7SlUbHb3F4YUbBtR2JDYh+eBIcOoaxU=


wifi:
  ssid: Hoth
  password: Hoth2024
  use_address: 192.168.3.181
  manual_ip:
    static_ip: 192.168.3.181
    gateway: 192.168.3.1
    subnet: 255.255.255.0
    dns1: 192.168.3.1

packages:
  music_dashboard: !include devices/guition-esp32-p4-jc8012p4a1/packages.yaml
  site_defaults: !include common/setup/site_defaults.yaml

