substitutions:
  name: "media-player"
  friendly_name: "Bedroom Media Player"
  media_player: "media_player.bedroom_sonos"

esphome:
  name_add_mac_suffix: true

api:
  encryption:
    key: xmPceR2fDbDBuiNyUcJ8hxoTn43suzcU18aAX/IAo5U=

wifi:
  ssid: "Hoth"
  password: "Hoth2024"
  use_address: 192.168.3.180
  manual_ip:
    static_ip: 192.168.3.180
    gateway: 192.168.3.1
    subnet: 255.255.255.0
    dns1: 192.168.3.1
packages:
  music_dashboard: !include devices/guition-esp32-p4-jc4880p443/packages-90.yaml
  site_defaults: !include common/setup/site_defaults.yaml
